#!/usr/bin/env ruby
require 'tmpdir' 
require 'digest/md5'
require 'highline/import'

gof3r_path = File.join(File.expand_path(File.dirname(__FILE__)), 'vendor', 'gof3r')

def usage
  puts "usage:"
  puts "  copy <ruby_name>"
  puts
  puts "  ruby_name is the Ruby version to copy -- (e.g. 'ruby-2.2.2')"
  exit(1)
end

def ruby_name
  usage unless ARGV[0]
  return ARGV[0]
end

def heroku_stack cf_stack
  mappings = {
    'cflinuxfs2' => 'cedar-14'
  }
  mappings.fetch(cf_stack)
end

def cf_stacks
  %w{cflinuxfs2}
end

def get_source_ruby_binary cf_stack, target_directory
  Dir.chdir(target_directory) do
    `wget -q https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/#{heroku_stack(cf_stack)}/#{ruby_name}.tgz`
    File.join(target_directory, "#{ruby_name}.tgz")
  end
end

def get_target_ruby_binary cf_stack, target_directory
  Dir.chdir(target_directory) do
    # wget always writes to the -O file, we remove it if wget couldnt find the file.
    `wget -q https://buildpacks.cloudfoundry.org/ruby/binaries/#{cf_stack}/#{ruby_name}.tgz -O #{ruby_name}.tgz.target || rm -rf #{ruby_name}.tgz.target`
    File.join(target_directory, "#{ruby_name}.tgz.target")
  end
end

cf_stacks.each do |stack| 
  Dir.mktmpdir do |temp_dir|
    source_ruby_path = get_source_ruby_binary(stack, temp_dir)
    source_md5 = Digest::MD5.file(source_ruby_path).hexdigest

    target_ruby_path = get_target_ruby_binary(stack, temp_dir)

    if File.exist?(target_ruby_path) then
      target_md5 = Digest::MD5.file(target_ruby_path).hexdigest

      puts "#{ruby_name} already exists on s3 for the '#{stack}' stack."
      puts "source md5: #{source_md5}"
      puts "target md5: #{target_md5}"

      exit(1) unless HighLine.agree("Are you sure you want to override the target? [yes|no]")
    end

    Dir.chdir(temp_dir) do
      output = `#{gof3r_path} cp #{ruby_name}.tgz s3://pivotal-buildpacks/ruby/binaries/#{stack}/#{ruby_name}.tgz 2>&1`
      raise "Could not put binary on s3:\n\nOutput from command:\n\n#{output}" unless $?.success?
    end

    puts "uri: https://buildpacks.cloudfoundry.org/ruby/binaries/#{stack}/#{ruby_name}.tgz"
    md5 = Digest::MD5.file("#{temp_dir}/#{ruby_name}.tgz").hexdigest
    puts "md5: #{md5}"
    puts "cf_stacks: \n  - #{stack}\n\n"
  end
end
