source 'https://rubygems.org'

ruby '<%= ruby_version %>', engine: 'jruby', engine_version: '<%= engine_version %>'

gem 'sinatra'
gem 'eventmachine'
gem 'bcrypt'
gem 'webrick'

gem 'jdbc-mysql'
gem 'jdbc-postgres'
